all: lessons

lessons:
	cd lesson_01; shards; ./build.sh
	cd lesson_02; shards; ./build.sh
	cd lesson_03; shards; ./build.sh
	cd lesson_04; shards; ./build.sh
	cd lesson_05; shards; ./build.sh
	cd lesson_06; shards; ./build.sh
	cd lesson_07; shards; ./build.sh
	cd lesson_08; shards; ./build.sh
	cd lesson_09; shards; ./build.sh
	cd lesson_10; shards; ./build.sh
	cd lesson_11; shards; ./build.sh
	cd lesson_12; shards; ./build.sh
	cd lesson_13; shards; ./build.sh
	cd lesson_14; shards; ./build.sh
	cd lesson_15; shards; ./build.sh
	cd lesson_16; shards; ./build.sh
	cd lesson_17; shards; ./build.sh
	cd lesson_18; shards; ./build.sh
	cd lesson_19; shards; ./build.sh
	cd lesson_20; shards; ./build.sh
	cd lesson_21; shards; ./build.sh
	cd lesson_22; shards; ./build.sh
	cd lesson_23; shards; ./build.sh
	cd lesson_24; shards; ./build.sh
	cd lesson_25; shards; ./build.sh
	cd lesson_26; shards; ./build.sh
	cd lesson_27; shards; ./build.sh
	cd lesson_28; shards; ./build.sh
	cd lesson_29; shards; ./build.sh

